# This action triggers a workflow in docs repository to pull and copy file changes from a given repository.

name: Tigger Pull docs
description: Triggers a workflow in caraml-dev/docs to pull and copy file changes from an input repository.

inputs:
  module:
    required: true
    description: 'name of caraml component'
  git_https:
    required: true
    description: 'value for https to git repo'
  doc_folder:
    required: true
    description: 'folder to copy over'
    default: 'docs'
  branch:
    required: true
    description: 'branch name to get files from'
    default: 'main'
  credentials:
    required: true
    description: 'Github Personal Access Token for write access to caraml-dev/docs'

runs:
  using: composite
  steps:
  - name: Trigger Sync Workflow
    uses: actions/github-script@v6
    with:
      github-token: ${{ inputs.credentials }}
      script: |
        await github.rest.actions.createWorkflowDispatch({
          owner: 'caraml-dev',
          repo: 'docs',
          workflow_id: 'pull_docs.yml',
          ref: 'main',
          inputs: {
            module: '${{ inputs.module }}',
            git_https: '${{ inputs.git_https }}',
            doc_folder: '${{ inputs.doc_folder }}',
            branch: '${{ inputs.branch }}',
          },
        })
