# This workflow tries to pull docs changes from given repo

name: Pull Docs CI

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
    inputs:
      module:
        required: true
        description: 'module name'
      git_https:
        required: true
        description: 'value for https to git repo'      
      doc_folder:
        required: true
        description: 'folder to copy over'
        default: 'docs'
      branch:
        required: true
        description: 'branch name to get files from'
        default: 'main'
  repository_dispatch:

jobs:
  sync-docs:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Caraml repo
        uses: actions/checkout@v3
        with:
          ref: main

      - name: Sync changes from model repos
        run: |
          git remote add -f -t ${{ github.event.inputs.branch }} --no-tags ${{ github.event.inputs.module }} ${{ github.event.inputs.git_https }}
          git rm -rf module/${{ github.event.inputs.module }}
          git read-tree --prefix=module/${{ github.event.inputs.module }} -u ${{ github.event.inputs.module }}/${{ github.event.inputs.branch }}:${{ github.event.inputs.doc_folder }}
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name github-actions
            git config user.email github-actions@github.com
            git add .
            git commit -m "sync ${{ github.event.inputs.module }} docs: $(date +'%Y-%m-%d')"
            git push
          else
            echo "Nothing to commit"
          fi          
