# This workflow triggers update in caraml doc

name: Trigger Caraml doc update

on:
  workflow_call:
    inputs:
      module:
        required: true
        description: 'module name'
        type: string
      git_https:
        required: true
        description: 'value for https to git repo'
        type: string
      doc_folder:
        required: true
        description: 'folder to copy over'
        default: 'docs'
        type: string
      branch:
        required: true
        description: 'branch name to get files from'
        default: 'main'
        type: string

jobs:
  trigger-sync:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/github-script@v6
      with:
        github-token: ${{ secrets.CARAML_SYNC }}
        script: |
          await github.rest.actions.createWorkflowDispatch({
            owner: 'caraml-dev',
            repo: 'docs',
            workflow_id: 'pull_docs.yml',
            ref: 'main',
            inputs: {
              module: <module>,
              git_https: <.git>,
              doc_folder: 'docs',
              branch: 'main',
            },
          })
